# Generated by Django 4.2.5 on 2023-09-24 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0005_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Watchlist',
            new_name='watchlist',
        ),
    ]
