# Generated by Django 4.2.5 on 2023-09-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0007_review_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avg_numbering',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
    ]
